### ISSUE TITLE
Add tag to pushed card for tracking

### ISSUE THREAD

**Issue by nateraw** [osanseviero/diffuse-it#1]
Any time after the default card was pushed after training, you can add this to track # of models shared using this repo :)

```python
from modelcards import ModelCard

card = ModelCard.load(repo_id)
card.data.tags.append("🧨 Diffuse It")
card.push_to_hub(repo_id)
```

[Example Repo Output](https://huggingface.co/nateraw/my-aurora)

**Comment by osanseviero** [comment]
Great idea!

**Comment by osanseviero** [comment]
Thanks! Solved in https://github.com/osanseviero/diffuse-it/commit/33c39e191543288b746fdd356ca90eefa5463812
